version: '3.3'

services:
  # Traefik reverse proxying
  reverse-proxy:
    image: traefik:v2.0.6
    container_name: stalkerlog-rp
    restart: on-failure
    ports:
      - 80:80
      - 8080:8080
    volumes:
      # Dynamic configuration
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Static configuration
      - ./traefik.toml:/etc/traefik/traefik.toml

  # MySQL DB
  api-db:
    image: mysql:5.7.28
    container_name: stalkerlog-db
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password --max-allowed-packet=300M
    environment:
      MYSQL_DATABASE: stalkerlog
      MYSQL_ROOT_PASSWORD: pwd
    ports:
      - 3306:3306
    labels:
      - "traefik.enable=false"

  # Main API for stalkerlog app
  stalkerlog:
    build: images/stalkerlog/
    container_name: stalkerlog
    restart: on-failure
    environment:
        spring_profiles_active: docker
    depends_on:
      - api-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.main.entrypoints=web"
      - "traefik.http.routers.main.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.services.main.loadbalancer.server.port=8080"

  # MySQL DB
  auth-db:
    image: mysql:5.7.28
    container_name: stalkerlog-auth-db
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password --max-allowed-packet=300M
    environment:
      MYSQL_DATABASE: stalkerlog-auth
      MYSQL_ROOT_PASSWORD: pwd
    ports:
      - 3307:3306
    labels:
      - "traefik.enable=false"

  # Auth API for stalkerlog app
  stalkerlog-auth:
    build: images/stalkerlog-auth/
    container_name: stalkerlog-auth
    restart: on-failure
    environment:
        spring_profiles_active: docker
    depends_on:
      - auth-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.routers.auth.rule=Host(`localhost`) && PathPrefix(`/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
