package ch.heigvd.amt.stalkerlog.api.endpoints;

import ch.heigvd.amt.stalkerlog.api.CitiesApi;
import ch.heigvd.amt.stalkerlog.api.model.City;
import ch.heigvd.amt.stalkerlog.entities.CityEntity;
import ch.heigvd.amt.stalkerlog.repositories.CityRepository;
import io.swagger.annotations.Api;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;

import java.util.ArrayList;
import java.util.List;

/**
 * Spring controller to implement operations generated by codegen
 *
 * @author Alison Savary, Luc Wachter
 */
@Controller
@Api(tags = "cities")
public class CitiesApiController implements CitiesApi {
    @Autowired
    CityRepository cityRepository;

    @Override
    public ResponseEntity<List<City>> getCities() {
        List<City> countries = new ArrayList<>();
        for (CityEntity cityEntity : cityRepository.findAll()) {
            countries.add(toCity(cityEntity));
        }
        return ResponseEntity.ok(countries);
    }

    private City toCity(CityEntity entity) {
        City city = new City();
        city.setName(entity.getName());
        city.setCountryId(entity.getCountry().getId());
        return city;
    }
}
