package ch.heigvd.amt.stalkerlog.api.endpoints;

import ch.heigvd.amt.stalkerlog.api.CitiesApi;
import ch.heigvd.amt.stalkerlog.api.model.City;
import ch.heigvd.amt.stalkerlog.entities.CityEntity;
import ch.heigvd.amt.stalkerlog.repositories.CityRepository;
import io.swagger.annotations.Api;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;

import javax.validation.Valid;
import java.util.ArrayList;
import java.util.List;

/**
 * Spring controller to implement operations generated by codegen
 *
 * @author Alison Savary, Luc Wachter
 */
@Controller
@Api(tags = "cities")
public class CitiesApiController implements CitiesApi {
    @Autowired
    CityRepository cityRepository;

    @Override
    public ResponseEntity<List<City>> getCities(@Valid Integer page, @Valid Integer pageSize) {
        List<City> cities = new ArrayList<>();
        for (CityEntity cityEntity : cityRepository.findAllByOrderByName(PageRequest.of(page - 1, pageSize))) {
            cities.add(toCity(cityEntity));
        }
        HttpHeaders responseHeaders = new HttpHeaders();
        responseHeaders.set("Pagination-NumberOfItems", String.valueOf(cityRepository.count()));
        responseHeaders.set("Pagination-Next", "/cities?page=" + (page + 1) + "&pageSize="+ pageSize);
        return ResponseEntity.ok()
                .headers(responseHeaders)
                .body(cities);
    }

    private City toCity(CityEntity entity) {
        City city = new City();
        city.setName(entity.getName());
        city.setCountryId(entity.getCountry().getId());
        return city;
    }
}
