package ch.heigvd.amt.stalkerlog.api.endpoints;

import ch.heigvd.amt.stalkerlog.api.CountriesApi;
import ch.heigvd.amt.stalkerlog.entities.CountryEntity;
import ch.heigvd.amt.stalkerlog.api.model.Country;
import ch.heigvd.amt.stalkerlog.repositories.CountryRepository;
import io.swagger.annotations.Api;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;

import java.util.ArrayList;
import java.util.List;

/**
 * Spring controller to implement operations generated by codegen
 *
 * @author Alison Savary, Luc Wachter
 */
@Controller
@Api(tags = "cities")
public class CountriesApiController implements CountriesApi {
    @Autowired
    CountryRepository countryRepository;

    public ResponseEntity<List<Country>> getCountries() {
        List<Country> countries = new ArrayList<>();
        for (CountryEntity countryEntity : countryRepository.findAll()) {
            countries.add(toCountry(countryEntity));
        }
        return ResponseEntity.ok(countries);
    }

    private Country toCountry(CountryEntity entity) {
        Country country = new Country();
        country.setName(entity.getName());
        country.setCountryCode(entity.getCountryCode());
        return country;
    }
}
