package ch.heigvd.amt.stalkerlog.api.endpoints;

import ch.heigvd.amt.stalkerlog.api.StarsApi;
import ch.heigvd.amt.stalkerlog.api.model.Star;
import ch.heigvd.amt.stalkerlog.entities.StarEntity;
import ch.heigvd.amt.stalkerlog.repositories.StarRepository;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiParam;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.PageRequest;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Spring controller to implement operations generated by codegen
 *
 * @author Alison Savary, Luc Wachter
 */
@Controller
@Api(tags = "stars")
public class StarsApiController implements StarsApi {
    @Autowired
    StarRepository starRepository;

    @Autowired
    private HttpServletRequest request;

    @Override
    public ResponseEntity<Void> postStar(@ApiParam(value = "", required = true) @Valid @RequestBody Star star) {
        // Create entity with owner id
        StarEntity newStarEntity = toStarEntity(star, (Long) request.getAttribute("userId"));
        starRepository.save(newStarEntity);

        URI location = ServletUriComponentsBuilder
            .fromCurrentRequest().path("/{id}")
            .buildAndExpand(newStarEntity.getId()).toUri();

        return ResponseEntity.created(location).build();
    }

    @Override
    public ResponseEntity<List<Star>> getStars(@Valid Integer page, @Valid Integer pageSize) {
        List<Star> stars = new ArrayList<>();
        long owner = (Long) request.getAttribute("userId");

        for (StarEntity starEntity :
            starRepository.findAllByOwnerOrderByName(owner, PageRequest.of(page - 1, pageSize))) {
            stars.add(toStar(starEntity));
        }

        HttpHeaders responseHeaders = new HttpHeaders();
        responseHeaders.set("Pagination-NumberOfItems", String.valueOf(starRepository.count()));
        responseHeaders.set("Pagination-Next", "/stars?page=" + (page + 1) + "&pageSize=" + pageSize);
        return ResponseEntity.ok()
            .headers(responseHeaders)
            .body(stars);
    }

    @Override
    public ResponseEntity<Star> getStar(Integer id) {
        Optional<StarEntity> starEntity = starRepository.findById(Long.valueOf(id));
        long owner = (Long) request.getAttribute("userId");

        // Star exists in database
        if (starEntity.isPresent()) {
            Star star = toStar(starEntity.get());

            // Check if this star belongs to that user
            if (owner != starEntity.get().getOwner()) {
                return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
            }

            return ResponseEntity.ok(star);
        } else {
            return ResponseEntity.notFound().build();
        }
    }

    @Override
    public ResponseEntity<Void> putStar(Integer id, @Valid Star star) {
        long owner = (Long) request.getAttribute("userId");
        StarEntity updatedEntity = toStarEntity(star, owner);

        Optional<StarEntity> starEntity = starRepository.findById(Long.valueOf(id));

        // Star exists in database
        if (starEntity.isPresent()) {
            // Check if this star belongs to that user
            if (owner != starEntity.get().getOwner()) {
                return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
            }

            updatedEntity.setId(id);
            starRepository.save(updatedEntity);
            return ResponseEntity.ok().build();
        } else {
            return ResponseEntity.notFound().build();
        }
    }

    @Override
    public ResponseEntity<Void> deleteStar(Integer id) {
        Optional<StarEntity> starEntity = starRepository.findById(Long.valueOf(id));
        long owner = (Long) request.getAttribute("userId");

        // Star exists in database
        if (starEntity.isPresent()) {
            // Check if this star belongs to that user
            if (owner != starEntity.get().getOwner()) {
                return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
            }

            starRepository.deleteById(Long.valueOf(id));
            return ResponseEntity.status(204).build();
        } else {
            return ResponseEntity.notFound().build();
        }
    }

    private StarEntity toStarEntity(Star star, long owner) {
        StarEntity entity = new StarEntity();
        entity.setName(star.getName());
        entity.setPlatform(star.getPlatform());
        entity.setOwner(owner);
        return entity;
    }

    private Star toStar(StarEntity entity) {
        Star star = new Star();
        star.setName(entity.getName());
        star.setPlatform(entity.getPlatform());
        return star;
    }
}
