package ch.heigvd.amt.stalkerlog.api.endpoints;

import ch.heigvd.amt.stalkerlog.api.UsersApi;
import ch.heigvd.amt.stalkerlog.api.model.User;
import ch.heigvd.amt.stalkerlog.api.util.UserUtils;
import ch.heigvd.amt.stalkerlog.entities.UserEntity;
import ch.heigvd.amt.stalkerlog.repositories.UserRepository;
import io.swagger.annotations.Api;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import java.util.Optional;

/**
 * Spring controller to implement operations generated by codegen
 *
 * @author Alison Savary, Luc Wachter
 */
@Controller
@Api(tags = "users")
public class UsersApiController implements UsersApi {
    @Autowired
    private UserRepository userRepository;

    @Autowired
    private HttpServletRequest request;

    @Override
    public ResponseEntity<Void> putUser(Integer id, @Valid User user) {
        UserEntity userEntity = UserUtils.toUserEntity(user);

        if (request.getAttribute("userId") != Long.valueOf(id)) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
        }

        // User exists in database
        if (userRepository.findById(Long.valueOf(id)).isPresent()) {
            // TODO PROBABLY NOT HOW IT SHOULD BE DONE
            userEntity.setId(id);
            userRepository.save(userEntity);
            return ResponseEntity.ok().build();
        }

        return ResponseEntity.notFound().build();
    }

    @Override
    public ResponseEntity<User> getUser(Integer id) {
        Optional<UserEntity> userEntity = userRepository.findById(Long.valueOf(id));

        if (request.getAttribute("userId") != Long.valueOf(id)) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
        }

        if (userEntity.isPresent()) {
            User user = UserUtils.toUser(userEntity.get());
            return ResponseEntity.ok(user);
        }

        return ResponseEntity.notFound().build();
    }

    @Override
    public ResponseEntity<Void> deleteUser(Integer id) {
        if (request.getAttribute("userId") != Long.valueOf(id)) {
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
        }

        if (userRepository.findById(Long.valueOf(id)).isPresent()) {
            userRepository.deleteById(Long.valueOf(id));
            return ResponseEntity.status(204).build();
        }

        return ResponseEntity.notFound().build();
    }
}
